---
apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  selector:
    app: products-api
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-api
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: products-api
spec:
  protocol: "http"
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: db-configmap
# data:
#   config: |
#     {
#       "db_connection": "host=postgres port=5432 user=postgres password=password dbname=products sslmode=disable",
#       "bind_address": ":9090",
#       "metrics_address": ":9103"
#     }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'products-api'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/products-api'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {
          {{ with secret "database/creds/products-api" -}}
            "db_connection": "host=postgres port=5432 user={{ .Data.username }} password={{ .Data.password }} dbname=products sslmode=disable",
            "bind_address": ":9090",
            "metrics_address": ":9103"
          {{- end }}
          }
    spec:
      serviceAccountName: products-api
      # volumes:
      # - name: config
      #   configMap:
      #     name: db-configmap
      #     items:
      #     - key: config
      #       path: conf.json
      containers:
        - name: products-api
          image: hashicorpdemoapp/product-api:v0.0.17
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "CONFIG_FILE"
              value: "/vault/secrets/db-creds"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
